// Dynamic path
POST http://localhost:8080/v1/lectures/create
Content-Type: application/json
Authorization: Bearer {insert valid token} 

{
    "Title" : "Rest title",
    "Brief" : "Rest brief",
    "Content" : "Rest content"
}

###
GET http://localhost:8080/v1/lectures/get
Content-Type: application/json
Authorization: Bearer {insert valid token} 

###

GET http://localhost:8080/v1/lectures/get/3
Content-Type: application/json
Authorization: Bearer {insert valid token} 

###

GET http://localhost:8080/v1/lectures/myLectures
Content-Type: application/json
Authorization: Bearer {insert valid token} 
###