// Dynamic path
PUT http://localhost:8080/v1/profile/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MTcsIkVtYWlsIjoidGVzdDE3QHRlc3QuY29tIiwiaWF0IjoxNjUzMjM1NTY2LCJleHAiOjE2NTMzMjE5NjZ9.hC6MklE9pRRfMCjrXh_vju-5fniyaWkkfzs9DQJ4u0A

{
    "Password" : "Password",
    "FirstName" : "FirsName",
    "LastName" : "LastName",
    "DoB": "2022-05-22"
}
###

GET http://localhost:8080/v1/profile/get/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MTcsIkVtYWlsIjoidGVzdDE3QHRlc3QuY29tIiwiaWF0IjoxNjUzMjM1NTY2LCJleHAiOjE2NTMzMjE5NjZ9.hC6MklE9pRRfMCjrXh_vju-5fniyaWkkfzs9DQJ4u0A
###

