// Dynamic path
PUT http://localhost:8080/v1/profile/update/unknown
Content-Type: application/json
Authorization: Bearer {insert valid token} 

{
    "Password" : "Password",
    "FirstName" : "FirsName",
    "LastName" : "LastName",
    "DoB": "2022-05-22"
}
###

GET http://localhost:8080/v1/profile/get/1
Content-Type: application/json
Authorization: Bearer {insert valid token} 
###

