// Dynamic path
PUT http://localhost:8080/v1/profile/update/unknown
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MjksIkVtYWlsIjoidGVzdDI1QHRlc3QuY29tIiwiaWF0IjoxNjUzNzMwOTMzLCJleHAiOjE2NTQzMzU3MzN9.27kUDn9QUGIZvsn6mt_uWKBcnV35lLOS8wpvrQYFaG8

{
    "Password" : "Password",
    "FirstName" : "FirsName",
    "LastName" : "LastName",
    "DoB": "2022-05-22"
}
###

GET http://localhost:8080/v1/profile/get/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MjksIkVtYWlsIjoidGVzdDI1QHRlc3QuY29tIiwiaWF0IjoxNjUzNzMwOTMzLCJleHAiOjE2NTQzMzU3MzN9.27kUDn9QUGIZvsn6mt_uWKBcnV35lLOS8wpvrQYFaG8
###

